mod anchors;
mod attr_refs;
pub(crate) mod collect_text;
pub mod customize_subs;
mod diagnose_document;
pub mod directives;
mod heading_level;
mod parse_attr_list;
mod parse_author_line;
mod parse_block;
mod parse_book_part;
mod parse_doc_attrs;
mod parse_doc_header;
mod parse_inlines;
mod parse_list;
mod parse_revision_line;
pub mod parse_section;
mod section_id;
mod table;
mod time;
