pub(crate) mod collect_text;
mod parse_attr_list;
mod parse_author_line;
mod parse_block;
mod parse_doc_attrs;
mod parse_doc_header;
mod parse_inlines;
mod parse_inlines_utils;
mod parse_list;
mod parse_revision_line;
pub mod parse_section;
