[package]
name = "dr-html-wasm"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
wasm-bindgen = "0.2.84"
asciidork-parser = { path = "../parser", version = "0.25.0" }
asciidork-eval = { path = "../eval", version = "0.25.0" }
asciidork-core = { path = "../core", version = "0.23.0" }
asciidork-dr-html-backend = { path = "../dr-html-backend", version = "0.25.0" }

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.7", optional = true }

[dev-dependencies]
wasm-bindgen-test = "0.3.34"

# [profile.release]
# # Tell `rustc` to optimize for small code size.
# opt-level = "s"
