[package]
name = "asciidork-meta"
version = "0.5.0"
edition = "2021"
description = "Asciidork document meta"
license = "MIT"

[dependencies]
lazy_static = "1.4.0"

[lints]
workspace = true

[lib]
doctest = false
