[package]
name = "asciidork-opts"
version = "0.3.3"
edition = "2021"
description = "Asciidork opts"
license = "MIT"

[dependencies]
asciidork-ast = { path = "../ast", version = "0.5.0" }
asciidork-meta = { path = "../meta", version = "0.5.0" }

[lints]
workspace = true

