name: basic-ci

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  check:
    strategy:
      matrix:
        target: ['ubuntu-latest', 'windows-latest']
    runs-on: ${{ matrix.target }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.89.0
        with:
          components: rustfmt, clippy
      - name: version
        run: rustc --version
      - name: check
        run: cargo check
      - name: clippy
        run: cargo clippy
      - name: fmt
        run: cargo fmt -- --check
      - name: test
        run: cargo test --all --no-fail-fast
      - name: build
        run: cargo build
      - name: wasm
        env:
          RUSTFLAGS: -D warnings -A unused-imports
        run: |
          npm install -g wasm-pack@0.12.1
          cd dr-html-wasm && wasm-pack build --target web

  tck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.89.0
      - name: build
        run: |
          cd tck
          cargo build
      - uses: actions/setup-node@v4
        with:
          node-version: '23'
      - name: checkout-tck
        run:
          git clone --depth 1
          https://gitlab.eclipse.org/eclipse/asciidoc-lang/asciidoc-tck
      - name: build-tck
        run: |
          cd asciidoc-tck
          npm ci
          npm run dist
      - name: run-tck
        run: |
          cd asciidoc-tck
          node ./harness/bin/asciidoc-tck.js cli \
            --adapter-command "$GITHUB_WORKSPACE/target/debug/asciidork-tck"

  acceptance:
    runs-on: ubuntu-latest
    steps:
      - name: install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: '9.4.0'
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.89.0
      - name: build
        run: cargo build
      - uses: actions/checkout@v4
        with:
          repository: 'jaredh159/asciidork-rx-html-acceptance'
          path: acceptance
      - name: install
        run: cd acceptance && pnpm install
      - name: accept
        run: |
          cd acceptance
          node ./check.js "$GITHUB_WORKSPACE/target/debug/asciidork" --verbose

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings

concurrency:
  group: ${{ github.ref }}-ci
  cancel-in-progress: true
